/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
import * as i0 from '@angular/core';
import * as i1 from './organizationchart';
export declare const OrganizationChartModuleNgFactory: i0.NgModuleFactory<i1.OrganizationChartModule>;
export declare const RenderType_OrganizationChart: i0.RendererType2;
export declare function View_OrganizationChart_0(_l: any): i0.ɵViewDefinition;
export declare function View_OrganizationChart_Host_0(_l: any): i0.ɵViewDefinition;
export declare const OrganizationChartNgFactory: i0.ComponentFactory<i1.OrganizationChart>;
export declare const RenderType_OrganizationChartNode: i0.RendererType2;
export declare function View_OrganizationChartNode_0(_l: any): i0.ɵViewDefinition;
export declare function View_OrganizationChartNode_Host_0(_l: any): i0.ɵViewDefinition;
export declare const OrganizationChartNodeNgFactory: i0.ComponentFactory<i1.OrganizationChartNode>;
