/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './gmap';
import * as i2 from '@angular/common';
export const GMapModuleNgFactory:i0.NgModuleFactory<i1.GMapModule> = i0.ɵcmf(i1.GMapModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(512,i2.CommonModule,
          i2.CommonModule,([] as any[])),i0.ɵmpd(512,i1.GMapModule,i1.GMapModule,([] as any[]))]);
    });
const styles_GMap:any[] = ([] as any[]);
export const RenderType_GMap:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_GMap,
    data:{}});
export function View_GMap_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'div',([] as any[]),
      [[8,'className',0]],(null as any),(null as any),(null as any),(null as any))),
      i0.ɵdid(278528,(null as any),0,i2.NgStyle,[i0.KeyValueDiffers,i0.ElementRef,
          i0.Renderer],{ngStyle:[0,'ngStyle']},(null as any))],(_ck,_v) => {
    var _co:i1.GMap = _v.component;
    const currVal_1:any = _co.style;
    _ck(_v,1,0,currVal_1);
  },(_ck,_v) => {
    var _co:i1.GMap = _v.component;
    const currVal_0:any = _co.styleClass;
    _ck(_v,0,0,currVal_0);
  });
}
export function View_GMap_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'p-gmap',([] as any[]),
      (null as any),(null as any),(null as any),View_GMap_0,RenderType_GMap)),i0.ɵdid(8699904,
      (null as any),0,i1.GMap,[i0.ElementRef,i0.IterableDiffers,i0.ChangeDetectorRef,
          i0.NgZone],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const GMapNgFactory:i0.ComponentFactory<i1.GMap> = i0.ɵccf('p-gmap',i1.GMap,
    View_GMap_Host_0,{style:'style',styleClass:'styleClass',options:'options',overlays:'overlays'},
    {onMapClick:'onMapClick',onOverlayClick:'onOverlayClick',onOverlayDragStart:'onOverlayDragStart',
        onOverlayDrag:'onOverlayDrag',onOverlayDragEnd:'onOverlayDragEnd',onMapReady:'onMapReady',
        onMapDragEnd:'onMapDragEnd',onZoomChanged:'onZoomChanged'},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovV29ya3NwYWNlL3ByaW1lbmcvc3JjL2FwcC9jb21wb25lbnRzL2dtYXAvZ21hcC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Xb3Jrc3BhY2UvcHJpbWVuZy9zcmMvYXBwL2NvbXBvbmVudHMvZ21hcC9nbWFwLnRzIiwibmc6Ly8vQzovV29ya3NwYWNlL3ByaW1lbmcvc3JjL2FwcC9jb21wb25lbnRzL2dtYXAvZ21hcC50cy5HTWFwLmh0bWwiLCJuZzovLy9DOi9Xb3Jrc3BhY2UvcHJpbWVuZy9zcmMvYXBwL2NvbXBvbmVudHMvZ21hcC9nbWFwLnRzLkdNYXBfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2IFtuZ1N0eWxlXT1cInN0eWxlXCIgW2NsYXNzXT1cInN0eWxlQ2xhc3NcIj48L2Rpdj4iLCI8cC1nbWFwPjwvcC1nbWFwPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTthQUFBO3FCQUFBOztJQUFLO0lBQUwsV0FBSyxTQUFMOzs7SUFBdUI7SUFBdkIsV0FBdUIsU0FBdkI7Ozs7b0JDQUE7TUFBQSwrRUFBQTtNQUFBO21CQUFBO0lBQUE7Ozs7Ozs7In0=
