/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
import * as i0 from '@angular/core';
import * as i1 from './spinner';
export declare const SpinnerModuleNgFactory: i0.NgModuleFactory<i1.SpinnerModule>;
export declare const RenderType_Spinner: i0.RendererType2;
export declare function View_Spinner_0(_l: any): i0.ɵViewDefinition;
export declare function View_Spinner_Host_0(_l: any): i0.ɵViewDefinition;
export declare const SpinnerNgFactory: i0.ComponentFactory<i1.Spinner>;
