/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './schedule';
import * as i2 from '@angular/common';
export const ScheduleModuleNgFactory:i0.NgModuleFactory<i1.ScheduleModule> = i0.ɵcmf(i1.ScheduleModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(512,i2.CommonModule,
          i2.CommonModule,([] as any[])),i0.ɵmpd(512,i1.ScheduleModule,i1.ScheduleModule,
          ([] as any[]))]);
    });
const styles_Schedule:any[] = ([] as any[]);
export const RenderType_Schedule:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_Schedule,
    data:{}});
export function View_Schedule_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'div',([] as any[]),
      [[8,'className',0]],(null as any),(null as any),(null as any),(null as any))),
      i0.ɵdid(278528,(null as any),0,i2.NgStyle,[i0.KeyValueDiffers,i0.ElementRef,
          i0.Renderer],{ngStyle:[0,'ngStyle']},(null as any))],(_ck,_v) => {
    var _co:i1.Schedule = _v.component;
    const currVal_1:any = _co.style;
    _ck(_v,1,0,currVal_1);
  },(_ck,_v) => {
    var _co:i1.Schedule = _v.component;
    const currVal_0:any = _co.styleClass;
    _ck(_v,0,0,currVal_0);
  });
}
export function View_Schedule_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'p-schedule',([] as any[]),
      (null as any),(null as any),(null as any),View_Schedule_0,RenderType_Schedule)),
      i0.ɵdid(9420800,(null as any),0,i1.Schedule,[i0.ElementRef,i0.IterableDiffers],
          (null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const ScheduleNgFactory:i0.ComponentFactory<i1.Schedule> = i0.ɵccf('p-schedule',
    i1.Schedule,View_Schedule_Host_0,{events:'events',header:'header',style:'style',
        styleClass:'styleClass',rtl:'rtl',weekends:'weekends',hiddenDays:'hiddenDays',
        fixedWeekCount:'fixedWeekCount',weekNumbers:'weekNumbers',businessHours:'businessHours',
        height:'height',contentHeight:'contentHeight',aspectRatio:'aspectRatio',eventLimit:'eventLimit',
        defaultDate:'defaultDate',editable:'editable',droppable:'droppable',eventStartEditable:'eventStartEditable',
        eventDurationEditable:'eventDurationEditable',defaultView:'defaultView',allDaySlot:'allDaySlot',
        allDayText:'allDayText',slotDuration:'slotDuration',slotLabelInterval:'slotLabelInterval',
        snapDuration:'snapDuration',scrollTime:'scrollTime',minTime:'minTime',maxTime:'maxTime',
        slotEventOverlap:'slotEventOverlap',nowIndicator:'nowIndicator',dragRevertDuration:'dragRevertDuration',
        dragOpacity:'dragOpacity',dragScroll:'dragScroll',eventOverlap:'eventOverlap',
        eventConstraint:'eventConstraint',locale:'locale',timezone:'timezone',timeFormat:'timeFormat',
        eventRender:'eventRender',dayRender:'dayRender',navLinks:'navLinks',options:'options'},
    {onDayClick:'onDayClick',onDrop:'onDrop',onEventClick:'onEventClick',onEventMouseover:'onEventMouseover',
        onEventMouseout:'onEventMouseout',onEventDragStart:'onEventDragStart',onEventDragStop:'onEventDragStop',
        onEventDrop:'onEventDrop',onEventResizeStart:'onEventResizeStart',onEventResizeStop:'onEventResizeStop',
        onEventResize:'onEventResize',onViewRender:'onViewRender',onViewDestroy:'onViewDestroy'},
    ([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovV29ya3NwYWNlL3ByaW1lbmcvc3JjL2FwcC9jb21wb25lbnRzL3NjaGVkdWxlL3NjaGVkdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1dvcmtzcGFjZS9wcmltZW5nL3NyYy9hcHAvY29tcG9uZW50cy9zY2hlZHVsZS9zY2hlZHVsZS50cyIsIm5nOi8vL0M6L1dvcmtzcGFjZS9wcmltZW5nL3NyYy9hcHAvY29tcG9uZW50cy9zY2hlZHVsZS9zY2hlZHVsZS50cy5TY2hlZHVsZS5odG1sIiwibmc6Ly8vQzovV29ya3NwYWNlL3ByaW1lbmcvc3JjL2FwcC9jb21wb25lbnRzL3NjaGVkdWxlL3NjaGVkdWxlLnRzLlNjaGVkdWxlX0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBbbmdTdHlsZV09XCJzdHlsZVwiIFtjbGFzc109XCJzdHlsZUNsYXNzXCI+PC9kaXY+IiwiPHAtc2NoZWR1bGU+PC9wLXNjaGVkdWxlPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7YUFBQTtxQkFBQTs7SUFBSztJQUFMLFdBQUssU0FBTDs7O0lBQXVCO0lBQXZCLFdBQXVCLFNBQXZCOzs7O29CQ0FBO01BQUE7YUFBQTtVQUFBO0lBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
