/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
import * as i0 from '@angular/core';
import * as i1 from './slider';
export declare const SliderModuleNgFactory: i0.NgModuleFactory<i1.SliderModule>;
export declare const RenderType_Slider: i0.RendererType2;
export declare function View_Slider_0(_l: any): i0.ɵViewDefinition;
export declare function View_Slider_Host_0(_l: any): i0.ɵViewDefinition;
export declare const SliderNgFactory: i0.ComponentFactory<i1.Slider>;
