/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
import * as i0 from '@angular/core';
import * as i1 from './inputmask';
export declare const InputMaskModuleNgFactory: i0.NgModuleFactory<i1.InputMaskModule>;
export declare const RenderType_InputMask: i0.RendererType2;
export declare function View_InputMask_0(_l: any): i0.ɵViewDefinition;
export declare function View_InputMask_Host_0(_l: any): i0.ɵViewDefinition;
export declare const InputMaskNgFactory: i0.ComponentFactory<i1.InputMask>;
