/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
import * as i0 from '@angular/core';
import * as i1 from './progressbar';
export declare const ProgressBarModuleNgFactory: i0.NgModuleFactory<i1.ProgressBarModule>;
export declare const RenderType_ProgressBar: i0.RendererType2;
export declare function View_ProgressBar_0(_l: any): i0.ɵViewDefinition;
export declare function View_ProgressBar_Host_0(_l: any): i0.ɵViewDefinition;
export declare const ProgressBarNgFactory: i0.ComponentFactory<i1.ProgressBar>;
