/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
import * as i0 from '@angular/core';
import * as i1 from './paginator';
export declare const PaginatorModuleNgFactory: i0.NgModuleFactory<i1.PaginatorModule>;
export declare const RenderType_Paginator: i0.RendererType2;
export declare function View_Paginator_0(_l: any): i0.ɵViewDefinition;
export declare function View_Paginator_Host_0(_l: any): i0.ɵViewDefinition;
export declare const PaginatorNgFactory: i0.ComponentFactory<i1.Paginator>;
