/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
import * as i0 from '@angular/core';
import * as i1 from './togglebutton';
export declare const ToggleButtonModuleNgFactory: i0.NgModuleFactory<i1.ToggleButtonModule>;
export declare const RenderType_ToggleButton: i0.RendererType2;
export declare function View_ToggleButton_0(_l: any): i0.ɵViewDefinition;
export declare function View_ToggleButton_Host_0(_l: any): i0.ɵViewDefinition;
export declare const ToggleButtonNgFactory: i0.ComponentFactory<i1.ToggleButton>;
