/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
import * as i0 from '@angular/core';
import * as i1 from './datalist';
export declare const DataListModuleNgFactory: i0.NgModuleFactory<i1.DataListModule>;
export declare const RenderType_DataList: i0.RendererType2;
export declare function View_DataList_0(_l: any): i0.ɵViewDefinition;
export declare function View_DataList_Host_0(_l: any): i0.ɵViewDefinition;
export declare const DataListNgFactory: i0.ComponentFactory<i1.DataList>;
