/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
import * as i0 from '@angular/core';
import * as i1 from './orderlist';
export declare const OrderListModuleNgFactory: i0.NgModuleFactory<i1.OrderListModule>;
export declare const RenderType_OrderList: i0.RendererType2;
export declare function View_OrderList_0(_l: any): i0.ɵViewDefinition;
export declare function View_OrderList_Host_0(_l: any): i0.ɵViewDefinition;
export declare const OrderListNgFactory: i0.ComponentFactory<i1.OrderList>;
