/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
import * as i0 from '@angular/core';
import * as i1 from './dropdown';
export declare const DropdownModuleNgFactory: i0.NgModuleFactory<i1.DropdownModule>;
export declare const RenderType_Dropdown: i0.RendererType2;
export declare function View_Dropdown_0(_l: any): i0.ɵViewDefinition;
export declare function View_Dropdown_Host_0(_l: any): i0.ɵViewDefinition;
export declare const DropdownNgFactory: i0.ComponentFactory<i1.Dropdown>;
